# Generated by Django 4.2.16 on 2024-10-16 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comentario_fch_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fch_creado',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 21, 14, 15, 484712, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 21, 14, 15, 484001, tzinfo=datetime.timezone.utc)),
        ),
    ]
